$token = "eyJhbGciOiJIUzUxMiJ9.eyJwZXJtaXNzaW9ucyI6WyJyZXZpZXc6YmF0Y2giLCJyZXZpZXc6c3RhdGlzdGljcyIsImFwcGxpY2F0aW9uOmJ1bGtfb3BlcmF0aW9uIiwicG9zaXRpb246Zm9ybV9jb25maWciLCJleGFtOmVkaXQiLCJ0ZW5hbnQ6YmFja3VwOnNjaGVkdWxlIiwidGVuYW50OmJhY2t1cDpjcmVhdGUiLCJzdWJqZWN0OmVkaXQiLCJub3RpZmljYXRpb246aGlzdG9yeTp2aWV3IiwiZXhhbTpmb3JtX2NvbmZpZyIsInBvc2l0aW9uOmNyZWF0ZSIsInZlbnVlOnZpZXciLCJhcHBsaWNhdGlvbjp2aWV3OmFsbCIsInNjb3JlOnJlY29yZCIsInRlbXBsYXRlOnVwZGF0ZSIsInVzZXI6Y3JlYXRlOnRlbmFudCIsInNlYXQ6dmlldyIsInZlbnVlOnVwZGF0ZSIsInBpaTpleHBvcnQiLCJ0aWNrZXQ6dmFsaWRhdGUiLCJleGFtOmRlbGV0ZSIsImV4YW06c3RhcnQiLCJ0aWNrZXQ6YmF0Y2hfZ2VuZXJhdGUiLCJzY29yZTp1cGRhdGUiLCJyZXBvcnQ6ZXhwb3J0IiwidGVtcGxhdGU6ZGVsZXRlIiwic2NvcmU6YmF0Y2hfaW1wb3J0Iiwic2NvcmU6c3RhdGlzdGljcyIsInRpY2tldDp0ZW1wbGF0ZTp2aWV3IiwidXNlcjp0ZW5hbnQ6cm9sZTpncmFudCIsImV4YW06dmVudWVfbWFuYWdlIiwiZXhhbTpvcGVuIiwidGlja2V0OnRlbXBsYXRlOmRlbGV0ZSIsImZpbGU6dmlldyIsInRpY2tldDp0ZW1wbGF0ZTp1cGRhdGUiLCJ0ZW5hbnQ6YmFja3VwOmRvd25sb2FkIiwicGlpOmRlbGV0ZSIsInNlYXQ6YWxsb2NhdGUiLCJleGFtOnNjaGVkdWxlX21hbmFnZSIsImZpbGU6ZGVsZXRlIiwiaW50ZXJ2aWV3OnJlc3VsdCIsInBvc2l0aW9uOmVkaXQiLCJ2ZW51ZTpjcmVhdGUiLCJwYXltZW50OnZpZXciLCJpbnRlcnZpZXc6c2NoZWR1bGUiLCJwaWk6YW5vbnltaXplIiwicmVwb3J0OnZpZXciLCJzdWJqZWN0OnZpZXciLCJwYXltZW50OmNvbmZpZzp2aWV3Iiwibm90aWZpY2F0aW9uOnNlbmQiLCJyZXZpZXc6c2Vjb25kYXJ5Iiwic3RhdGlzdGljczp2aWV3IiwidGVuYW50OmJhY2t1cDpyZXN0b3JlIiwidGVuYW50OnVzZXJfbWFuYWdlIiwidGVtcGxhdGU6Y3JlYXRlIiwic3ViamVjdDpkZWxldGUiLCJ2ZW51ZTpkZWxldGUiLCJleGFtOmNvbXBsZXRlIiwidGVtcGxhdGU6dmlldyIsInBvc2l0aW9uOmRlbGV0ZSIsIm5vdGlmaWNhdGlvbjp2aWV3IiwidGlja2V0OmdlbmVyYXRlIiwidGlja2V0Omlzc3VlIiwiZXhhbTp2aWV3IiwiZXhhbTpjcmVhdGUiLCJ0ZW5hbnQ6YmFja3VwOnZlcmlmeSIsInN1YmplY3Q6Y3JlYXRlIiwiZXhhbTphZG1pbjptYW5hZ2UiLCJ0ZW5hbnQ6YmFja3VwOmRlbGV0ZSIsInJldmlldzpwcmltYXJ5IiwiZXhhbTpjbG9zZSIsInNlYXQ6dXBkYXRlIiwiYXVkaXQ6dmlldyIsInBpaTpwb2xpY3k6dmlldyIsImZpbGU6dXBsb2FkIiwiaW50ZXJ2aWV3OmNvbmR1Y3QiLCJzZWF0aW5nOmFsbG9jYXRlIiwicG9zaXRpb246dmlldyIsInZlbnVlOmxpc3QiLCJzY29yZTp2aWV3IiwidGVuYW50OmJhY2t1cDpsaXN0IiwidGlja2V0OmRvd25sb2FkIl0sInJvbGVzIjpbIlRFTkFOVF9BRE1JTiJdLCJ0ZW5hbnRJZCI6IjQ1ZjNkYmZlLTUxNGItNGE2Zi05ZDQxLTFhOWQ2MzBiY2EzZSIsImZ1bGxOYW1lIjoi5p2O5ZubIiwidG9rZW5UeXBlIjoiVEVOQU5UIiwidXNlcklkIjoiODAyZjZhMDUtMzc4NC00OGExLThjMjMtM2I3MDZkZDc4ZjYxIiwiZW1haWwiOiJkdWFucnVvQGV4YW1wbGUuY29tIiwidXNlcm5hbWUiOiJkdWFucnVvdGVzdDEiLCJzdGF0dXMiOiJBQ1RJVkUiLCJzdWIiOiJkdWFucnVvdGVzdDEiLCJpc3MiOiJleGFtLXJlZ2lzdHJhdGlvbi1zeXN0ZW0iLCJpYXQiOjE3NjQxMzQ2NjYsImV4cCI6MTc2NDIyMTA2Nn0.eDwCtbuSaiAusF9RmUsYvFK7C6-lFT0wtAcp9KrsNHvgVt3EX3_-6YUBO2lzpB2b-gWA0Ff0ZVhoXWQvt5g2sQ"

$parts = $token.Split('.')
$payload = $parts[1]
while ($payload.Length % 4 -ne 0) { $payload += "=" }
$bytes = [System.Convert]::FromBase64String($payload)
$json = [System.Text.Encoding]::UTF8.GetString($bytes)
$obj = $json | ConvertFrom-Json

Write-Host "=== Token Payload ===" -ForegroundColor Cyan
Write-Host "Username: $($obj.username)" -ForegroundColor Green
Write-Host "UserId: $($obj.userId)" -ForegroundColor Green
Write-Host "FullName: $($obj.fullName)" -ForegroundColor Green
Write-Host "Email: $($obj.email)" -ForegroundColor Green
Write-Host "Roles: $($obj.roles -join ', ')" -ForegroundColor Green
Write-Host "TenantId: $($obj.tenantId)" -ForegroundColor Green
Write-Host "TokenType: $($obj.tokenType)" -ForegroundColor Green
Write-Host "Issued At: $(Get-Date -UnixTimeSeconds $obj.iat -Format 'yyyy-MM-dd HH:mm:ss')" -ForegroundColor Gray
Write-Host "Expires At: $(Get-Date -UnixTimeSeconds $obj.exp -Format 'yyyy-MM-dd HH:mm:ss')" -ForegroundColor Gray
Write-Host "`nPermissions Count: $($obj.permissions.Count)" -ForegroundColor Yellow
Write-Host "Contains 'exam:view': $($obj.permissions -contains 'exam:view')" -ForegroundColor Yellow

