export enum ApplicationStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  AUTO_PASSED = 'AUTO_PASSED',
  AUTO_REJECTED = 'AUTO_REJECTED',
  PENDING_PRIMARY_REVIEW = 'PENDING_PRIMARY_REVIEW',
  PRIMARY_PASSED = 'PRIMARY_PASSED',
  PRIMARY_REJECTED = 'PRIMARY_REJECTED',
  PENDING_SECONDARY_REVIEW = 'PENDING_SECONDARY_REVIEW',
  APPROVED = 'APPROVED',
  SECONDARY_REJECTED = 'SECONDARY_REJECTED',
  PAID = 'PAID',
  TICKET_ISSUED = 'TICKET_ISSUED',
}
