// Permissions granted to all authenticated users (session + cross-cutting reads)
export const BASE_PERMISSIONS: string[] = [
  'application:view:own',
  'application:create',
  'file:upload',
  'file:view:own',
  'ticket:view:own',
  'payment:initiate',
  'session:user:read',
  'session:tenants:list',
  'session:refresh',
];

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  CANDIDATE: [
    'exam:view:public',
    'application:view:own',
    'application:update:own',
    'ticket:view:own',
    'payment:view:own',
    'profile:view:own',
    'profile:create',
    'profile:update',
    'profile:delete',
  ],
  SUPER_ADMIN: [
    'tenant:view:all',
    'tenant:create',
    'tenant:update',
    'tenant:delete',
    'user:manage',
    'user:view',
    'user:create',
    'user:update',
    'user:delete',
    'statistics:system:view',
    'exam:view',
    'exam:view:all',
    'exam:create',
    'exam:edit',
    'exam:delete',
    'exam:publish',
    'exam:open',
    'exam:close',
    'application:view',
    'application:view:all',
    'application:update',
    'application:delete',
    'review:view',
    'review:view:all',
    'review:perform',
    'review:primary',
    'review:secondary',
    'ticket:view',
    'ticket:view:all',
    'ticket:generate',
    'ticket:batch-generate',
    'seating:view',
    'seating:view:all',
    'seating:create',
    'seating:edit',
    'seating:delete',
    'seating:allocate',
    'file:view',
    'file:view:all',
    'file:delete',
    'position:view',
    'position:create',
    'position:edit',
    'position:delete',
    'profile:view:all',
    'payment:view:own',
    'payment:order:read',
  ],
  TENANT_ADMIN: [
    'exam:create',
    'exam:view',
    'exam:view:all',
    'exam:edit',
    'exam:delete',
    'exam:publish',
    'exam:open',
    'exam:close',
    'position:create',
    'position:view',
    'position:view:all',
    'position:edit',
    'position:delete',
    'application:view',
    'application:view:all',
    'application:update',
    'application:export',
    'review:view',
    'review:view:all',
    'review:assign',
    'ticket:view',
    'ticket:view:all',
    'ticket:generate',
    'ticket:batch-generate',
    'seating:view',
    'seating:view:all',
    'seating:create',
    'seating:allocate',
    'file:view',
    'file:view:all',
    'file:delete',
    'statistics:tenant:view',
    'user:view',
    'user:create',
    'profile:view:all',
    'payment:view:own',
    'payment:order:read',
  ],
  ADMIN: [
    'exam:create',
    'exam:view',
    'exam:view:all',
    'exam:edit',
    'exam:delete',
    'exam:publish',
    'exam:open',
    'exam:close',
    'position:create',
    'position:view',
    'position:view:all',
    'position:edit',
    'position:delete',
    'application:view',
    'application:view:all',
    'application:update',
    'application:export',
    'review:view',
    'review:view:all',
    'review:assign',
    'ticket:view',
    'ticket:view:all',
    'ticket:generate',
    'ticket:batch-generate',
    'seating:view',
    'seating:view:all',
    'seating:create',
    'seating:allocate',
    'file:view',
    'file:view:all',
    'file:delete',
    'statistics:tenant:view',
    'user:view',
    'user:create',
    'profile:view:all',
    'payment:view:own',
    'payment:order:read',
  ],
  PRIMARY_REVIEWER: [
    'review:primary',
    'review:view',
    'review:view:assigned',
    'review:perform',
    'application:view:assigned',
    // 审核队列：OPEN 考试列表、报名表模板、附件下载
    'exam:view',
    'file:view',
  ],
  SECONDARY_REVIEWER: [
    'review:secondary',
    'review:view',
    'review:view:assigned',
    'review:perform',
    'application:view:assigned',
    'exam:view',
    'file:view',
  ],
};

export function getPermissionsForRoles(roles: string[]): string[] {
  const permissions = new Set<string>(BASE_PERMISSIONS);
  for (const role of roles) {
    const rolePerms = ROLE_PERMISSIONS[role];
    if (rolePerms) {
      for (const perm of rolePerms) {
        permissions.add(perm);
      }
    }
  }
  return Array.from(permissions);
}
